// svelte-website/src/components/loader.svelte

<div id="loader" class="row justify-content-md-center">
      <div class="col col-auto-md">
        <div class="lds-facebook" id="inner-loader">
          <div></div>
          <div></div>
          <div></div>
        </div>
        <p class="lead" style="color : white;" id="message" />
      </div>

    </div>

<style>
/** Loading screen main CSS class**/
.lds-facebook {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}

.lds-facebook div {
  display: inline-block;
  position: absolute;
  left: 8px;
  width: 16px;
  background: #3FBD71;
  animation: lds-facebook 1.2s cubic-bezier(0, 0.5, 0.5, 1) infinite;
}

.lds-facebook div:nth-child(1) {
  left: 8px;
  animation-delay: -0.24s;
}

.lds-facebook div:nth-child(2) {
  left: 32px;
  animation-delay: -0.12s;
}

.lds-facebook div:nth-child(3) {
  left: 56px;
  animation-delay: 0;
}

@keyframes lds-facebook {
  0% {
    top: 8px;
    height: 64px;
  }

  50%,
  100% {
    top: 24px;
    height: 32px;
  }
}
</style>

// src/components/loader/loader.tsx
import React from 'react';
import './loader.css';

export default function Loader() {
  return (
    <div id="loader" className="row justify-content-md-center">
      <div className="col col-auto-md">
        <div className="lds-facebook" id="inner-loader">
          <div />
          <div />
          <div />
        </div>
        <p className="lead" id="message" style={{ color: 'white' }} />
      </div>
    </div>
  );
}
